# navbar
navbar:
  Archives: /archives/
  Tags: /tags/
  Tools: /tools/
  About: /about/

# copyright
since: 2011

# site
description: A simple theme for Hexo. 
language: en

theme_color: "#ffffff"

# author
author: 
  - name: Gitai
  - bio: Less is more.
  - headimg: /5354788.png

# search
search: 
    enable: false
    placeholder: Enter Key...

# sidebar
sidebar: 
  enable: false
  menus:
    -
      name: Gitai
      link: https://gitai.me/
      target: _blank

# comments
comments:
  post: true
  about: true
  #duoshuo_username:  yumemor
  #disqus_username: yumemor

# accounts support weibo/github/zhihu/twitter/douban/G+/facebook 
# Social links
social:
  email: mailto:i@gitai.me
  # stack-overflow:
  weibo: http://weibo.com/dphdjy/
  twitter: https://twitter.com/_gitai
  # facebook:
  github: https://github.com/GitaiQAQ
  # weibo: http://weibo.com/ahonn
  zhihu: https://www.zhihu.com/people/gitai
  rss: /atom.xml

analytics:
  baidu: false
  google: false